BEGIN
   ROLLBACK;
   /*sgc_accounts_pkg.prc_load_init;
   sgc_acl_actions_pkg.prc_load_init;
   sgc_contacts_pkg.prc_load_init;*/
   --
   sgc_accounts_pkg.prc_load;
   sgc_acl_actions_pkg.prc_load;
   sgc_contacts_pkg.prc_load;
   --
   --
   /*sgm_accounts_pkg.prc_load_init;
   sgm_acl_actions_pkg.prc_load_init;*/
   --
   sgm_accounts_pkg.prc_load;
   sgm_acl_actions_pkg.prc_load;
   --
   /*tst_bigtable_pkg.prc_load_init;*/
   --
   --tst_bigtable_pkg.prc_load;
   tst_smalltable_pkg.prc_load_stage;
   ROLLBACK;
   tst_smalltable_pkg.prc_load_diff;
   ROLLBACK;
   tst_smalltable_pkg.prc_load_hist;
   ROLLBACK;
END;
/