BEGIN
   /*sgc_accounts_pkg.prc_load_init;
   sgc_acl_actions_pkg.prc_load_init;
   sgc_contacts_pkg.prc_load_init;*/
   --
   sgc_accounts_pkg.prc_load;
   sgc_acl_actions_pkg.prc_load;
   sgc_contacts_pkg.prc_load;
   --
   --
   sgm_accounts_pkg.prc_load_init;
   sgm_acl_actions_pkg.prc_load_init;
   --
   sgm_accounts_pkg.prc_load;
   sgm_acl_actions_pkg.prc_load;
END;
/

ROLLBACK;