-- SugarCRM
REVOKE CONNECT ON SAMPLE FROM USER sugarcrm;

GRANT CONNECT ON SAMPLE TO USER sugarcrm;

COMMIT;


-- db2user
REVOKE CONNECT ON SAMPLE FROM USER db2user;

GRANT CONNECT ON SAMPLE TO USER db2user;

COMMIT;