DROP TABLE tab_test;

CREATE TABLE tab_test (
	COL_BOOLEAN BOOLEAN,
	--
	COL_BYTEINT BYTEINT,
	COL_SMALLINT SMALLINT,
	COL_INT INT,
	COL_BIGINT BIGINT,
	-
	COL_DECIMAL DECIMAL (38,10),
	COL_NUMERIC DECIMAL (38,10),
	COL_DOUBLE DOUBLE,
	COL_FLOAT FLOAT,
	COL_REAL REAL,
	-
	COL_CHAR CHAR(1000),
	COL_VARCHAR VARCHAR(1000),
	COL_NCHAR NCHAR(1000),
	COL_NVARCHAR NVARCHAR(1000),
	-
	COL_DATE DATE,
	COL_TIME TIME,
	COL_TIMETZ TIMETZ,
	COL_TIMESTAMP TIMESTAMP,
	COL_INTERVAL INTERVAL
);
