/* Formatted on 21/03/2014 11:55:52 (QP5 v5.227.12220.39754) */
BEGIN
   ENABLE.PRC_ENABLE_UTL ('DWHSTAGE');
   --ENABLE.PRC_disable_UTL ('DWHSTAGE');
   ENABLE.PRC_ENABLE_TRC ('DWHSTAGE');
   --ENABLE.PRC_disable_TRC ('DWHSTAGE');
   ENABLE.PRC_ENABLE_mes ('DWHSTAGE');
   --ENABLE.PRC_disable_mes ('DWHSTAGE');
   ENABLE.PRC_ENABLE_stg ('DWHSTAGE');
   --ENABLE.PRC_disable_stg ('DWHSTAGE');
END;
/